USE bankManagementSystem;

CREATE TABLE ACCOUNT (
	ACCOUNT_NUMBER VARCHAR(10) PRIMARY KEY,
    ACCOUNT_TYPE ENUM('saving', 'current') NOT NULL,
    ACCOUNT_CURRENT_BALANCE DECIMAL(15, 2) NOT NULL,
	ACCOUNT_IS_OPENED BOOLEAN NOT NULL DEFAULT FALSE,
    ACCOUNT_IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    ACCOUNT_OPENING_DATE DATE NOT NULL,
    
    ACCOUNT_LAST_LOGIN DATE NOT NULL,
    
    ACCOUNT_CUSTOMER_CNIC VARCHAR(13) NOT NULL,
    ACCOUNT_BRANCH_ID INT,
    
    FOREIGN KEY(ACCOUNT_CUSTOMER_CNIC)
		REFERENCES CUSTOMER(CUSTOMER_CNIC),
	
    FOREIGN KEY(ACCOUNT_BRANCH_ID)
		REFERENCES BRANCH(BRANCH_ID)
        ON DELETE SET NULL
);

ALTER TABLE ACCOUNT 
DROP ACCOUNT_IS_LOAN_ACTIVATED;

ALTER TABLE ACCOUNT 
MODIFY ACCOUNT_TYPE ENUM('saving', 'current', 'beneficiary') NOT NULL;

SELECT A.ACCOUNT_NUMBER, A.ACCOUNT_TYPE, A.ACCOUNT_CURRENT_BALANCE, A.ACCOUNT_OPENING_DATE, A.ACCOUNT_LAST_LOGIN, B.BRANCH_NAME
FROM ACCOUNT AS A
INNER JOIN
BRANCH AS B
ON B.BRANCH_ID = A.ACCOUNT_BRANCH_ID
WHERE A.ACCOUNT_IS_OPENED;

DROP TABLE ACCOUNT;

TRUNCATE TABLE ACCOUNT;

SELECT * FROM ACCOUNT;

UPDATE ACCOUNT SET ACCOUNT_IS_OPENED = true WHERE ACCOUNT_NUMBER   = "1100";


DESCRIBE ACCOUNT;
SELECT * FROM ACCOUNT
JOIN CUSTOMER
ON ACCOUNT.ACCOUNT_CUSTOMER_CNIC = CUSTOMER.CUSTOMER_CNIC;

SHOW TABLE STATUS LIKE 'ACCOUNT';

UPDATE ACCOUNT
SET ACCOUNT_CURRENT_BALANCE = "9"
WHERE ACCOUNT_NUMBER = "20";


INSERT INTO ACCOUNT (ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_CURRENT_BALANCE, ACCOUNT_IS_OPENED, 
ACCOUNT_IS_DELETED, ACCOUNT_OPENING_DATE, ACCOUNT_LAST_LOGIN, ACCOUNT_CUSTOMER_CNIC, ACCOUNT_BRANCH_ID)
VALUES (20, "current", 100.120, true, false, "2025-05-11", "2010-05-11","1234567891234", "1004");

-- BENEFICIRAY
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_CURRENT_BALANCE, ACCOUNT_IS_OPENED, 
ACCOUNT_IS_DELETED, ACCOUNT_OPENING_DATE, ACCOUNT_LAST_LOGIN, ACCOUNT_CUSTOMER_CNIC, ACCOUNT_BRANCH_ID)
VALUES (1100, "beneficiary", 0, true, false, "2025-05-11", "2010-05-11","696969", "1002");

UPDATE ACCOUNT SET ACCOUNT_IS_OPENED = false WHERE ACCOUNT_CUSTOMER_CNIC = "1111";

INSERT INTO ACCOUNT (ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_CURRENT_BALANCE, ACCOUNT_IS_OPENED, 
ACCOUNT_IS_DELETED, ACCOUNT_OPENING_DATE, ACCOUNT_LAST_LOGIN, ACCOUNT_CUSTOMER_CNIC, ACCOUNT_BRANCH_ID)
VALUES (80, "saving", 6969.69, false, false, "2095-05-11", "2090-05-11","1111", "1003");

INSERT INTO ACCOUNT (ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_CURRENT_BALANCE, ACCOUNT_IS_OPENED, 
ACCOUNT_IS_DELETED, ACCOUNT_OPENING_DATE, ACCOUNT_LAST_LOGIN, ACCOUNT_CUSTOMER_CNIC, ACCOUNT_BRANCH_ID)
VALUES (40, "current", 1.120, true, false, "2025-05-11", "2010-05-11","0987654321098", "1004");