USE bankManagementSystem;

CREATE TABLE ACCOUNT (
	ACCOUNT_NUMBER VARCHAR(10) PRIMARY KEY,
    ACCOUNT_TYPE ENUM('saving', 'current', 'beneficiary') NOT NULL,
    ACCOUNT_CURRENT_BALANCE DECIMAL(15, 2) NOT NULL DEFAULT 0,
	ACCOUNT_IS_OPENED BOOLEAN NOT NULL DEFAULT FALSE,
    ACCOUNT_IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    ACCOUNT_OPENING_DATE DATE NOT NULL DEFAULT (CURRENT_DATE),
    
    ACCOUNT_LAST_LOGIN DATE,  -- Can be updated on login
    
    ACCOUNT_CUSTOMER_CNIC VARCHAR(13) NOT NULL,
    ACCOUNT_BRANCH_ID INT,
    
    FOREIGN KEY (ACCOUNT_CUSTOMER_CNIC)
		REFERENCES CUSTOMER(CUSTOMER_CNIC),
	
    FOREIGN KEY (ACCOUNT_BRANCH_ID)
		REFERENCES BRANCH(BRANCH_ID)
        ON DELETE SET NULL
);

INSERT INTO ACCOUNT (ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_CURRENT_BALANCE, ACCOUNT_IS_OPENED, 
ACCOUNT_IS_DELETED, ACCOUNT_OPENING_DATE, ACCOUNT_LAST_LOGIN, ACCOUNT_CUSTOMER_CNIC, ACCOUNT_BRANCH_ID)
VALUES (80, "saving", 6969.69, false, false, "2095-05-11", "2090-05-11","1111", "1003");
