CREATE TABLE ADMIN (
	 ADMIN_ID INT PRIMARY KEY AUTO_INCREMENT,
	 ADMIN_MAIL VARCHAR(50) NOT NULL UNIQUE,
     ADMIN_PASSWORD VARCHAR(255) NOT NULL UNIQUE
)AUTO_INCREMENT = 10000;

SELECT * FROM ADMIN;