CREATE DATABASE bankManagementSystem;
USE bankManagementSystem;

CREATE TABLE CUSTOMER (
	CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(50) NOT NULL,
    CUSTOMER_MAIL VARCHAR(50) NOT NULL UNIQUE,
	CUSTOMER_PHONE VARCHAR(11) NOT NULL UNIQUE,
    CUSTOMER_CNIC VARCHAR(13) NOT NULL UNIQUE,
    CUSTOMER_DOB DATE,
    CUSTOMER_PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE STAFF (
	STAFF_ID INT PRIMARY KEY AUTO_INCREMENT,
    STAFF_NAME VARCHAR(50) NOT NULL,
    STAFF_MAIL VARCHAR(50) NOT NULL UNIQUE,
	STAFF_PHONE VARCHAR(11) NOT NULL UNIQUE,
    STAFF_CNIC VARCHAR(13) NOT NULL UNIQUE,
    STAFF_DOB DATE,
    STAFF_PASSWORD VARCHAR(255) NOT NULL,
    STAFF_BRANCH_ID INT,
    
    FOREIGN KEY (STAFF_BRANCH_ID)
		REFERENCES BRANCH(BRANCH_ID)
        ON DELETE SET NULL
);

SELECT * FROM STAFF;
TRUNCATE TABLE STAFF;
DROP TABLE STAFF;

CREATE TABLE ADMIN (
	 ADMIN_ID INT PRIMARY KEY AUTO_INCREMENT,
	 ADMIN_MAIL VARCHAR(50) NOT NULL UNIQUE,
     ADMIN_PASSWORD VARCHAR(255) NOT NULL UNIQUE
)AUTO_INCREMENT = 10000;

CREATE TABLE BRANCH (
	BRANCH_ID INT PRIMARY KEY AUTO_INCREMENT,
    BRANCH_NAME VARCHAR(50) NOT NULL,
    BRANCH_ADDRESS VARCHAR(50) NOT NULL,
    BRANCH_PHONE VARCHAR(11) NOT NULL UNIQUE,
    BRANCH_EMPLOYEE_COUNT INT DEFAULT 0
) AUTO_INCREMENT = 1001;

INSERT INTO BRANCH (BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE) VALUES
('Main City Branch', '123 Main St, Lahore', '03001234567'),
('Gulberg Branch', '45 Gulberg III, Lahore', '03019876543'),
('Johar Town Branch', '789 Johar Town, Lahore', '03111234567'),
('Model Town Branch', '234 Model Town, Lahore', '03211234567'),
('DHA Phase 6 Branch', '56 Z Block DHA, Lahore', '03331234567');

DROP TABLE BRANCH;
SELECT * FROM BRANCH;

