CREATE DATABASE bankManagementSystem;
USE bankManagementSystem;

CREATE TABLE CUSTOMER (
	CUSTOMER_CNIC VARCHAR(13) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(50) NOT NULL,
    CUSTOMER_MAIL VARCHAR(50) NOT NULL UNIQUE,
	CUSTOMER_PHONE VARCHAR(11) NOT NULL UNIQUE,
    CUSTOMER_DOB DATE,
    CUSTOMER_PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO CUSTOMER (CUSTOMER_CNIC, CUSTOMER_NAME, CUSTOMER_MAIL, CUSTOMER_PHONE, CUSTOMER_DOB, CUSTOMER_PASSWORD)
VALUES ("1234567891234","JOHN", "JOHN@MAIL.COM", "12341234", "2025-10-09", "1234");

DROP TABLE CUSTOMER;
SELECT * FROM CUSTOMER;

CREATE TABLE ACCOUNT (
	ACCOUNT_NUMBER VARCHAR(10) PRIMARY KEY,
    ACCOUNT_TYPE ENUM('saving', 'current') NOT NULL,
    ACCOUNT_CURRENT_BALANCE DECIMAL(15, 2) NOT NULL,
	ACCOUNT_IS_OPENED BOOLEAN NOT NULL DEFAULT FALSE,
    ACCOUNT_IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    ACCOUNT_OPENING_DATE DATE NOT NULL,
    
    ACCOUNT_CUSTOMER_CNIC VARCHAR(13) NOT NULL,
    ACCOUNT_BRANCH_ID INT,
    
    FOREIGN KEY(ACCOUNT_CUSTOMER_CNIC)
		REFERENCES CUSTOMER(CUSTOMER_CNIC),
	
    FOREIGN KEY(ACCOUNT_BRANCH_ID)
		REFERENCES BRANCH(BRANCH_ID)
        ON DELETE SET NULL
);

SELECT C.CUSTOMER_CNIC, C.CUSTOMER_NAME, C.CUSTOMER_MAIL, C.CUSTOMER_PHONE,
A.ACCOUNT_NUMBER, A.ACCOUNT_TYPE, A.ACCOUNT_OPENING_DATE, A.ACCOUNT_BRANCH_ID, B.BRANCH_NAME
FROM ACCOUNT AS A
INNER JOIN
CUSTOMER AS C
ON A.ACCOUNT_CUSTOMER_CNIC = C.CUSTOMER_CNIC
INNER JOIN
BRANCH AS B
ON B.BRANCH_ID = A.ACCOUNT_BRANCH_ID
WHERE !A.ACCOUNT_IS_OPENED;

SELECT * FROM ACCOUNT;

UPDATE ACCOUNT SET ACCOUNT_IS_OPENED = 0 WHERE ACCOUNT_NUMBER = "10";

INSERT INTO ACCOUNT (ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_CURRENT_BALANCE, ACCOUNT_IS_OPENED, 
ACCOUNT_IS_DELETED, ACCOUNT_OPENING_DATE, ACCOUNT_CUSTOMER_CNIC, ACCOUNT_BRANCH_ID)
VALUES (10, "saving", 20.2, false, false, "2025-05-11", "1234567891234", "1002");

CREATE TABLE STAFF (
	STAFF_ID INT PRIMARY KEY AUTO_INCREMENT,
    STAFF_NAME VARCHAR(50) NOT NULL,
    STAFF_MAIL VARCHAR(50) NOT NULL UNIQUE,
	STAFF_PHONE VARCHAR(11) NOT NULL UNIQUE,
    STAFF_CNIC VARCHAR(13) NOT NULL UNIQUE,
    STAFF_DOB DATE,
    STAFF_PASSWORD VARCHAR(295) NOT NULL,
    STAFF_BRANCH_ID INT,
    
    FOREIGN KEY (STAFF_BRANCH_ID)
		REFERENCES BRANCH(BRANCH_safi)
        ON DELETE SET NULL
);

SELECT * FROM STAFF;
TRUNCATE TABLE STAFF;
DROP TABLE STAFF;

CREATE TABLE ADMIN (
	 ADMIN_ID INT PRIMARY KEY AUTO_INCREMENT,
	 ADMIN_MAIL VARCHAR(50) NOT NULL UNIQUE,
     ADMIN_PASSWORD VARCHAR(255) NOT NULL UNIQUE
)AUTO_INCREMENT = 10000;

CREATE TABLE BRANCH (
	BRANCH_ID INT PRIMARY KEY AUTO_INCREMENT,
    BRANCH_NAME VARCHAR(50) NOT NULL,
    BRANCH_ADDRESS VARCHAR(50) NOT NULL,
    BRANCH_PHONE VARCHAR(11) NOT NULL UNIQUE,
    BRANCH_EMPLOYEE_COUNT INT DEFAULT 0
) AUTO_INCREMENT = 1001;

INSERT INTO BRANCH (BRANCH_NAME, BRANCH_ADDRESS, BRANCH_PHONE) VALUES
('Main City Branch', '123 Main St, Lahore', '03001234567'),
('Gulberg Branch', '45 Gulberg III, Lahore', '03019876543'),
('Johar Town Branch', '789 Johar Town, Lahore', '03111234567'),
('Model Town Branch', '234 Model Town, Lahore', '03211234567'),
('DHA Phase 6 Branch', '56 Z Block DHA, Lahore', '03331234567');

DROP TABLE BRANCH;
SELECT * FROM BRANCH;

