USE bankManagementSystem;

-- TRIGGERS FOR BANK MANAGEMENT SYSTEM

-- TRIGGERS
DELIMITER $$
CREATE TRIGGER INCREMENT_EMPLOYEE_COUNT
AFTER INSERT ON STAFF
FOR EACH ROW
BEGIN
	UPDATE BRANCH
	SET BRANCH_EMPLOYEE_COUNT = BRANCH_EMPLOYEE_COUNT +1
    WHERE BRANCH_ID = NEW.STAFF_BRANCH_ID;
END$$

DELIMITER ;

DELIMITER $$
CREATE TRIGGER DECREMENT_EMPLOYEE_COUNT
AFTER DELETE ON STAFF
FOR EACH ROW
BEGIN
	UPDATE BRANCH
	SET BRANCH_EMPLOYEE_COUNT = BRANCH_EMPLOYEE_COUNT -1
    WHERE BRANCH_ID = OLD.STAFF_BRANCH_ID;
END$$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER UPDATE_EMPLOYEE_COUNT
AFTER UPDATE ON STAFF
FOR EACH ROW
BEGIN
    -- Only update if the branch has actually changed
    IF OLD.STAFF_BRANCH_ID <> NEW.STAFF_BRANCH_ID THEN
        -- Decrease count from old branch
        UPDATE BRANCH
        SET BRANCH_EMPLOYEE_COUNT = BRANCH_EMPLOYEE_COUNT - 1
        WHERE BRANCH_ID = OLD.STAFF_BRANCH_ID;

        -- Increase count in new branch
        UPDATE BRANCH
        SET BRANCH_EMPLOYEE_COUNT = BRANCH_EMPLOYEE_COUNT + 1
        WHERE BRANCH_ID = NEW.STAFF_BRANCH_ID;
    END IF;
END$$

DELIMITER ;