CREATE TABLE BILLS (
	BENEFICIARY_ACCOUNT_NUMBER VARCHAR(10) NOT NULL,
    
    REFERENCE_NUMBER VARCHAR(10) PRIMARY KEY,
    CONSUMER_NAME VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    
    IS_PAID BOOLEAN DEFAULT FALSE,
    
    FOREIGN KEY(BENEFICIARY_ACCOUNT_NUMBER)
		REFERENCES ACCOUNT(ACCOUNT_NUMBER)
); 
