CREATE TABLE BILLS (
	BENEFICIARY_ACCOUNT_NUMBER VARCHAR(10) NOT NULL,
    
    REFERENCE_NUMBER VARCHAR(10) PRIMARY KEY,
    CONSUMER_NAME VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(15,2) NOT NULL,
    
    IS_PAID BOOLEAN DEFAULT FALSE,
    
    FOREIGN KEY(BENEFICIARY_ACCOUNT_NUMBER)
		REFERENCES ACCOUNT(ACCOUNT_NUMBER)
); 

INSERT INTO BILLS (BENEFICIARY_ACCOUNT_NUMBER, REFERENCE_NUMBER, CONSUMER_NAME, AMOUNT)
VALUES ("1100", "001", "Saad", 9765);

SELECT * FROM BILLS;
TRUNCATE TABLE BILLS;

UPDATE BILLS
SET IS_PAID = true
WHERE REFERENCE_NUMBER = "3";


-- FOR DASHBORAD DATA

-- UNPAID AMOUNT
SELECT SUM(AMOUNT) 
FROM BILLS
WHERE IS_PAID = false AND BENEFICIARY_ACCOUNT_NUMBER = "1100";

-- PAID AMOUNT
SELECT SUM(AMOUNT) 
FROM BILLS
WHERE IS_PAID = true AND BENEFICIARY_ACCOUNT_NUMBER = "1100";

-- UNPAID COUNT
SELECT COUNT(*) 
FROM BILLS
WHERE IS_PAID = false AND BENEFICIARY_ACCOUNT_NUMBER = "1100";

-- PAID COUNT
SELECT COUNT(*) 
FROM BILLS
WHERE IS_PAID = true AND BENEFICIARY_ACCOUNT_NUMBER = "1100";

-- LAST LOGIN
SELECT ACCOUNT_LAST_LOGIN
FROM ACCOUNT
WHERE ACCOUNT_NUMBER = "1100";

-- BENEFICIARY NAME
SELECT CUSTOMER_NAME
FROM ACCOUNT
JOIN CUSTOMER 
ON ACCOUNT_CUSTOMER_CNIC = CUSTOMER_CNIC
WHERE ACCOUNT_NUMBER = "1100";