USE bankManagementSystem;

CREATE TABLE CUSTOMER (
	CUSTOMER_CNIC VARCHAR(13) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(50) NOT NULL,
    CUSTOMER_MAIL VARCHAR(50) NOT NULL UNIQUE,
	CUSTOMER_PHONE VARCHAR(11) NOT NULL UNIQUE,
    CUSTOMER_DOB DATE,
    CUSTOMER_PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO CUSTOMER (CUSTOMER_CNIC, CUSTOMER_NAME, CUSTOMER_MAIL, CUSTOMER_PHONE, CUSTOMER_DOB, CUSTOMER_PASSWORD)
VALUES ("1234567891234","JOHN", "JOHN@MAIL.COM", "12341234", "2025-10-09", "1234");

DROP TABLE CUSTOMER;
SELECT * FROM CUSTOMER;