CREATE TABLE LOAN_APPLICATION (
    LOAN_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOAN_AMOUNT DECIMAL(15, 2) NOT NULL,
    LOAN_ACCOUNT_NUMBER VARCHAR(10) NOT NULL,
    LOAN_TENURE INT NOT NULL,
    LOAN_PURPOSE ENUM( 'Education', 'Business', 'Personal','Vehicle') NOT NULL,
    LOAN_APPLY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LOAN_NOTE VARCHAR(255),
    LOAN_IS_APPROVED BOOLEAN DEFAULT FALSE,
    
    FOREIGN KEY(LOAN_ACCOUNT_NUMBER) 
		REFERENCES ACCOUNT(ACCOUNT_NUMBER)
);