CREATE TABLE LOAN_APPLICATION (
    LOAN_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOAN_AMOUNT DECIMAL(15, 2) NOT NULL,
    LOAN_ACCOUNT_NUMBER VARCHAR(10) NOT NULL,
    LOAN_TENURE INT NOT NULL,
    LOAN_PURPOSE ENUM( 'Education', 'Business', 'Personal','Vehicle') NOT NULL,
    LOAN_APPLY_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    LOAN_NOTE VARCHAR(255),
    LOAN_IS_APPROVED BOOLEAN DEFAULT FALSE,
    
    FOREIGN KEY(LOAN_ACCOUNT_NUMBER) 
		REFERENCES ACCOUNT(ACCOUNT_NUMBER)
);

SELECT SUM(LOAN_AMOUNT)
FROM LOAN_APPLICATION
WHERE LOAN_ACCOUNT_NUMBER = "20" and LOAN_IS_APPROVED;

INSERT INTO LOAN_APPLICATION (LOAN_AMOUNT, LOAN_ACCOUNT_NUMBER, LOAN_TENURE, LOAN_PURPOSE, LOAN_APPLY_DATE, LOAN_NOTE) 
VALUES (878, "20", 12, "Vehicle", "2025-10-09", "I Need Vehicle Bruh!");

UPDATE LOAN_APPLICATION
SET LOAN_IS_APPROVED = false
WHERE LOAN_ID =3;

SELECT LOAN_ID, LOAN_AMOUNT, LOAN_TENURE, LOAN_PURPOSE, LOAN_APPLY_DATE, LOAN_IS_APPROVED 
FROM LOAN_APPLICATION WHERE LOAN_ACCOUNT_NUMBER = "20";

SELECT * FROM LOAN_APPLICATION;
DROP TABLE LOAN_APPLICATION;