USE bankManagementSystem;

CREATE TABLE STAFF (
	STAFF_ID INT PRIMARY KEY AUTO_INCREMENT,
    STAFF_NAME VARCHAR(50) NOT NULL,
    STAFF_MAIL VARCHAR(50) NOT NULL UNIQUE,
	STAFF_PHONE VARCHAR(11) NOT NULL UNIQUE,
    STAFF_CNIC VARCHAR(13) NOT NULL UNIQUE,
    STAFF_DOB DATE, 
    STAFF_PASSWORD VARCHAR(295) NOT NULL,
    STAFF_BRANCH_ID INT,
    
    FOREIGN KEY (STAFF_BRANCH_ID)
		REFERENCES BRANCH(BRANCH_ID)
        ON DELETE SET NULL
);

SELECT * FROM STAFF WHERE staff_id <> 6;

SELECT * FROM STAFF;
TRUNCATE TABLE STAFF;
DROP TABLE STAFF;