CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    
    ACCOUNT_NUMBER VARCHAR(10) NOT NULL, -- Owner
    TRANSACTION_TYPE ENUM('DEBIT', 'CREDIT') NOT NULL,
    TRANSACTION_AMOUNT DECIMAL(15,2) NOT NULL,
    TRANSACTION_DESCRIPTION VARCHAR(255),
    
    COUNTERPARTY_ACCOUNT VARCHAR(10) NOT NULL,
    
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER),
    FOREIGN KEY (COUNTERPARTY_ACCOUNT) REFERENCES ACCOUNT(ACCOUNT_NUMBER)
);
   
SELECT * FROM TRANSACTIONS
ORDER BY TIMESTAMP DESC;