CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    
    ACCOUNT_NUMBER VARCHAR(10) NOT NULL, -- Owner
    TRANSACTION_TYPE ENUM('DEBIT', 'CREDIT') NOT NULL,
    TRANSACTION_AMOUNT DECIMAL(15,2) NOT NULL,
    TRANSACTION_DESCRIPTION VARCHAR(255),
    
    COUNTERPARTY_ACCOUNT VARCHAR(10) NOT NULL,
    
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER),
    FOREIGN KEY (COUNTERPARTY_ACCOUNT) REFERENCES ACCOUNT(ACCOUNT_NUMBER)
);
   
SELECT * FROM TRANSACTIONS
ORDER BY TIMESTAMP DESC;

-- Sender's transaction: Account 20 sends money to 10
INSERT INTO transactions (ACCOUNT_NUMBER, TRANSACTION_TYPE, TRANSACTION_AMOUNT, TRANSACTION_DESCRIPTION, COUNTERPARTY_ACCOUNT)
VALUES ("20", 'DEBIT', 150.2, 'Sent to account 40', "40");

INSERT INTO transactions (ACCOUNT_NUMBER, TRANSACTION_TYPE, TRANSACTION_AMOUNT, TRANSACTION_DESCRIPTION, COUNTERPARTY_ACCOUNT)
VALUES ("40", 'CREDIT', 1, 'Recived from account 20', "20");

-- Receiver's transaction: Account 10 receives money from 20
INSERT INTO transactions (ACCOUNT_NUMBER, TRANSACTION_TYPE, TRANSACTION_AMOUNT, TRANSACTION_DESCRIPTION, COUNTERPARTY_ACCOUNT)
VALUES ("20", 'CREDIT', 1500.2, 'Received from account 40', "40");

DROP TABLE TRANSACTIONS;
TRUNCATE TABLE TRANSACTIONS;


SELECT
  T.TRANSACTION_TYPE,
  T.TRANSACTION_AMOUNT,
  T.TRANSACTION_DESCRIPTION,
  CP.ACCOUNT_NUMBER AS counterparty_account,
  CCP.CUSTOMER_NAME AS COUNTER_PARTY_NAME,
  T.TIMESTAMP
  
FROM TRANSACTIONS AS T
INNER JOIN ACCOUNT AS MP ON T.ACCOUNT_NUMBER = MP.ACCOUNT_NUMBER
INNER JOIN ACCOUNT AS CP ON T.COUNTERPARTY_ACCOUNT = CP.ACCOUNT_NUMBER

JOIN CUSTOMER AS CMP ON MP.ACCOUNT_CUSTOMER_CNIC = CMP.CUSTOMER_CNIC
JOIN CUSTOMER AS CCP ON CP.ACCOUNT_CUSTOMER_CNIC = CCP.CUSTOMER_CNIC
WHERE T.ACCOUNT_NUMBER = "20";
